let { base1:  _1 , base1protected:  p1  } = require('../tiles/tdm.js'),
    { bossSpawn:   b } = require('../tiles/siege.js'),
    { wall: WALL, nest:  n , normal:   _  } = require('../tiles/misc.js'),
    { rock:   r  } = require('../tiles/decoration.js'),
    { portal:  P   } = require('../tiles/portal.js'),

room = [
    [  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ],
    [  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ],
    [  _ ,  _ ,  _ ,  _ ,  _ ,WALL,WALL,WALL,WALL,  _ ,  _ ,  _ ,  _ ,  _ ,WALL,  _ ,WALL,WALL,WALL,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ],
    [  _ ,  _ ,  _ ,  _ ,  _ ,WALL,  r ,  r ,WALL,  _ ,  _ ,  _ ,  _ ,WALL,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,WALL,  _ ,  _ ,  _ ,  _ ],
    [  _ ,  _ ,  _ ,  _ ,  _ ,WALL,  r ,  r ,WALL,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ],
    [  _ ,  _ ,WALL,  _ ,  _ ,WALL,  _ ,WALL,WALL,WALL,WALL,WALL,WALL,  _ ,WALL,WALL,WALL,WALL,WALL,WALL,  _ ,WALL,  _ ,  _ ,  _ ],
    [  _ ,  _ ,  _ ,  _ ,  _ ,WALL,  r ,  r ,  r ,WALL,  _ ,  _ ,  _ ,  _ ,  _ ,WALL,  b ,  b ,  b ,WALL,  _ ,  _ ,  _ ,  _ ,  _ ],
    [  _ ,  _ ,  _ ,  _ ,  _ ,WALL,  r , P  ,  r ,WALL,WALL,WALL,  _ ,WALL,WALL,WALL,  _ ,  _ ,  _ ,WALL,  _ ,WALL,  _ ,WALL,WALL],
    [  _ ,  _ ,  _ ,  _ ,  _ ,WALL,  r ,  r ,  r ,WALL,  _ ,  _ ,  _ ,  _ ,  _ ,WALL,WALL,  _ ,WALL,WALL,  _ ,  _ ,  n ,  n ,  n ],
    [ P  ,  _ ,WALL,  _ ,  _ ,WALL,  r ,  r ,  r ,WALL,  _ , _1 , _1 , _1 ,  _ ,WALL,  _ ,  _ ,  _ ,WALL,  _ ,WALL,  n ,  n ,  n ],
    [  _ ,  _ ,  _ ,  _ ,  _ ,WALL,  r ,  r ,  r ,  _ ,  _ , _1 , p1 , _1 ,  _ ,  _ ,  _ , P  ,  _ ,WALL,  _ ,WALL,  n , P  ,  n ],
    [  _ ,  _ ,  _ ,  _ ,  _ ,WALL,  r ,  r ,  r ,WALL,  _ , _1 , _1 , _1 ,  _ ,WALL,  _ ,  _ ,  _ ,WALL,  _ ,WALL,  n ,  n ,  n ],
    [  _ ,  _ ,  _ ,  _ ,  _ ,WALL,WALL,  r ,WALL,WALL,  _ ,  _ ,  _ ,  _ ,  _ ,WALL,WALL,WALL,WALL,WALL,  _ ,  _ ,  n ,  n ,  n ],
    [  _ ,  _ ,WALL,  _ ,  _ ,WALL,  r ,  r ,  r ,WALL,  _ ,WALL,WALL,WALL,  _ ,WALL,  _ ,  _ ,  _ ,  _ ,  _ ,WALL,  _ ,WALL,WALL],
    [  _ ,  _ ,  _ ,  _ ,  _ ,WALL,  r ,  r ,  r ,WALL,  r ,  n ,  n ,  n ,  r ,WALL,  _ ,  _ ,  _ ,  _ ,WALL,  _ ,  _ ,  _ ,  _ ],
    [  _ ,  _ ,  _ ,  _ ,  _ ,WALL,WALL,WALL,  _ ,WALL,WALL,WALL,WALL,WALL,WALL,WALL,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ],
    [  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,WALL,  r ,WALL,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ],
    [  _ ,  _ ,WALL,  _ ,  _ ,  _ ,  _ ,WALL,  _ ,WALL,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,WALL,  _ ,  _ ,  _ ,  _ ,  _ , P  ,  _ ,  _ ],
    [  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,WALL,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ],
    [  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ,  _ ],
];

module.exports = room;